version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - daming-pgxer:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    networks:
      - daming-pgxer
volumes:
  daming-pgxer:
    external: true

networks:
  daming-pgxer:
    external: true
